<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form>
                <div class="form-group">
                    <label>Type</label>
                    <select class="form-control">
                        <option value="general">Anfrage</option>
                        <option value="tech">Technische Anfrage</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label>Message</label>
                    <textarea class="form-control" placeholder="Your Message"></textarea>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input">
                    <label class="form-check-label">
                        AGB
                        <a href="/datenschutz.html" target="_blank">Zur Datenschutz Erklärung</a>
                    </label>
                </div>
                <button type="reset" class="btn btn-primary float-right">Reset</button>
                <button class="btn btn-primary float-right" onclick="goBack()">Back</button>
                <button type="submit" class="btn btn-primary float-right">Submit</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>
