<div class="container">
    <div class="row">
        <div class="form-contact">
            <form action="<?= $block->getPostUrl(); ?>" method="post">
                <div class="form-group">
                    <label>Type</label>
                    <select name="type" class="form-control field-type">
                        <?php foreach($block->getTypes() as $key): ?>
                            <option value="<?= strtolower($key) ?>"><?= ucfirst($key) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Email address</label>
                    <input required type="email" name="email" class="form-control field-email"
                           placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label>Message</label>
                    <textarea required name="message" class="form-control field-message"
                              placeholder="Your Message"></textarea>
                </div>
                <div class="form-check">
                    <input type="checkbox" name="agb" id="checkbox-agb" required class="form-check-input field-agb">
                    <label class="form-check-label" for="checkbox-agb">
                        AGB
                        <p><a href="/privacy-policy-cookie-restriction-mode/" target="_blank">Zur Datenschutz
                                Erklärung</a></p>
                    </label>
                </div>
                <div class="btn-group float-left">
                    <button type="reset" class="btn btn-secondary">Reset</button>
                    <button class="btn btn-primary" onclick="window.history.back()">Back</button>
                </div>
                <div class="btn-group float-right">
                    <button id="supportSend" type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
