<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form action="<?= $block->getPostUrl(); ?>" method="post">
                <div class="form-group">
                    <label>Type</label>
                    <select name="type" class="form-control field-type">
                        <?php var_dump($block->getPostUrl()); ?>
                        <?php foreach($block->getTypes() as $key): ?>
                            <?php var_dump($key); ?>
                        <?php endforeach; ?>

                        <option value="general">Anfrage</option>
                        <option value="tech">Technische Anfrage</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Email address</label>
                    <input required type="email" name="email" class="form-control field-email"
                           placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label>Message</label>
                    <textarea required name="message" class="form-control field-message"
                              placeholder="Your Message"></textarea>
                </div>
                <div class="form-check">
                    <input type="checkbox" name="agb" required class="form-check-input field-agb">
                    <label class="form-check-label">
                        AGB
                        <a href="/datenschutz.html" target="_blank">Zur Datenschutz Erklärung</a>
                    </label>
                </div>
                <div class="btn-group float-left">
                    <button type="reset" class="btn btn-primary">Reset</button>
                    <button class="btn btn-primary" onclick="window.history.back()">Back</button>
                </div>
                <div class="form-group d-none">
                    <input name="botdetect" required class="form-control field-botdetect"
                           value="<?= $block->getFormKey(); ?>">
                </div>
                <div class="btn-group float-right">
                    <button id="supportSend" type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>
